#!/usr/bin/env python
import sys
import os
import time
from subprocess import *
import psutil

# -f file.txt : output information to a file rather than stderr
# -d          : debug mode, prints the logs in prompt

out = sys.stderr
FILE = False
DEBUG = False
TIMER = False

## Parsing args
child_args = []
i = 1
while i < len(sys.argv):
    if sys.argv[i] == '-f':
        i += 1
        out = open(sys.argv[i], 'w')
        FILE = True
    elif sys.argv[i] == '-t':
        TIMER = True
    elif sys.argv[i] == '-d':
        DEBUG = True
    else:
        child_args.append(sys.argv[i])
    i += 1

#Creating child command from the given parameters
child_command = ' '.join(child_args)


def log(msg):
    if DEBUG:
        print("memusg: {}".format(msg))
    if FILE:
        out.write("memusg: {} \n".format(msg))

log(child_args)

# Sampling function: executes ps to get the given process memory
def get_vsize(sid):
    vsize = 0
    proc = Popen(['ps', '-o', 'vsize=', '--sid', str(sid)], stdout=PIPE, stderr=None, shell=False)
    (stdout, _stderr) = proc.communicate()
    # Sum the size of each 
    for line in stdout.split():
        vsize += int(line.strip())
    return vsize

def measure_memory_usage(pid):
    # Obtenir des informations sur l'utilisation de la mémoire du processus
    process = psutil.Process(pid)
    mem_info = process.memory_info()
    log("Process pid is : {}".format(pid))
    log("Process mem is : {}".format(mem_info))
    vms = mem_info.vms

    # Obtenir une liste de tous les forks du processus
    forks = process.children(recursive=True)

    # Pour chaque fork, mesurer l'utilisation de la mémoire
    for fork in forks:
        fork_mem_info = fork.memory_info()
        log("Child pid is {}".format(fork.pid))
        log("Child mem is {}".format(fork_mem_info)) 
        vms += fork_mem_info.vms

    return vms

# Parent process infos
pid = os.getpid()
sid = os.getsid(pid)
pgid = os.getpgid(pid)
log("Pre-fork: PID is {} ; PGID is {} ; SID is {}".format(pid, pgid, sid))

# Starting time for execution time
if TIMER:
    startTime = time.time()

# Creating child process to execute child command
fork_pid = os.fork()

# We are in the child process
if fork_pid == 0:
    # Setting up child process
    pid = os.getpid()
    sid = os.getsid(pid)
    pgid = os.getpgid(pid)
    log("Post-fork: PID is {} ; PGID is {} ; SID is {}".format(pid, pgid, sid))

    log("Trying to init our own session".format(pid, pgid))
    os.setsid()
    sid = os.getsid(pid)
    pgid = os.getpgid(pid)
    log("Post-session init: PID is {} ; PGID is {} ; SID is {}".format(pid, pgid, sid))
        
    log("Starting child: {}".format(child_command))
    proc = Popen(child_command, stdin=None, stdout=None, stderr=None, env=None, shell=True)

    # Logging peak memory usage 
    vmpeak = -1
    while proc.returncode == None:
        vmpeak = max(measure_memory_usage(pid), vmpeak)
        log("Waiting for child to exit. vmpeak={}".format(vmpeak))
        proc.poll()     # Check if child process has finished
        time.sleep(0.01) # Time in seconds (float)
    
    out.write("memusg: vmpeak: {} \n".format(vmpeak))

    status = proc.returncode
    log("Child process returned {}".format(status))
    sys.exit(status)

# We are in parent process
else:
    # Wait for child process to finish
    (_fork_pid, full_status) = os.waitpid(fork_pid, 0)
    status = full_status >> 8
    log("Fork returned {}".format(status))
    if TIMER:
        executionTime = (time.time() - startTime)
        out.write("Execution time : {} s\n".format(executionTime))
    out.close()
    sys.exit(status)
